language: android

notifications:
  email:
    - jmols.mobile@gmail.com

android:
  components:
    - build-tools-23.0.0
    - android-23
    - extra-android-m2repository

script:
  - echo "Travis branch is $TRAVIS_BRANCH"
  - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
